### ISSUE TITLE
Support expiration

### ISSUE THREAD

**Issue by dvirsky** [RedisLabs/spark-redis#11]
Proposed API change:

right now the API for saving RDDs to redis looks like:

```scala
def toRedisKV(kvs: RDD[(String, String)])
``` 

We should just change it to:

```scala
def toRedisKV(kvs: RDD[(String, String)], ttl:Int = 0)
```

Where 0 means no expiration.

Same applies for all other save funcs.

**Comment by sunheehnus** [comment]
+1

**Comment by shenzhun** [comment]
+1, nice!

**Comment by dvirsky** [comment]
added in #15. closing

**Comment by sjtuxiaoming** [comment]
+1 good!
