### ISSUE TITLE
[question] how to read a redis hash key with many fields into a DataFrame?

### ISSUE THREAD

**Issue by buxizhizhoum** [RedisLabs/spark-redis#111]
Hi, I am trying to read Redis hashes with python API, and when I am reading a hash key with many fields, it return a flat DataFrame just like this(the first row is minutes and seconds in type of MM:SS, the second row is values):
+-----+------+------+-----+------+------+------+-----+------+
|2658|2718|2617|2648|2708|2628|2607|2728|2638|
+-----+------+------+-----+------+------+------+-----+------+
| 0.10| 0.20|0.10 |0.30| 0.20 |  0.10| 0.20| 0.10| 0.30|
+-----+------+------+-----+------+------+------+-----+------+ 

My Redis hash key is: 20181102_0815_pttl, and the timestamp(in format of MM:SS) of the value is regarded as fields, just like below:

field  value
2658   0.1
2718   0.2
2617   0.1

The method I use to read data from Redis is:

load_df = spark\
        .read\
        .format("org.apache.spark.sql.redis")\
        .option("keys.pattern", "20181102_0815_pttl") \
        .option("infer.schema", True)\
        .load()

However I prefer a DataFrame like below to do further process, 

time value
2658   0.1
2718   0.2
2617   0.1
2648   0.3
2708   0.2
2628   0.1
2607   0.2
2728   0.1
2638   0.3

Considering the fact that transform the DataFrame is not efficient, and my question is: Is there some configs that could help to read the DataFram that is not flat?

**Comment by fe2s** [comment]
Hi,
This is not currently supported, but something we may introduce in the future. At the moment it's a one-to-one mapping between DataFrame row and redis hash. 

It is possible to load such kind of a hash with `fromRedisHash()` into RDD with Scala, but RDD functions are not supported in Python.

**Comment by buxizhizhoum** [comment]
Hi, thanks for your kind reply, and I will try to find whether there is other method to solve it.
