### ISSUE TITLE
spark redis key column mapping not working for existing hash

### ISSUE THREAD

**Issue by jper80** [RedisLabs/spark-redis#114]
I am following the example from spark-redis connector documentation to create Dataframes from a an existing hash.

The hash built as follows:
127.0.0.1:6379> hset person:1 name John age 30
(integer) 2
127.0.0.1:6379> hset person:2 name Peter age 45
(integer) 2
127.0.0.1:6379> hset person:3 name James age 40

The code to read the hash is as follows -

    SparkSession spark = SparkSession
        .builder()
        .appName("MyApp")
        .master("local[*]")
        .config("spark.redis.host", "localhost")
        .config("spark.redis.port", "6379")
         .getOrCreate();
    Dataset<Row> df = spark.read()
       .format("org.apache.spark.sql.redis")
       .schema(new StructType(new StructField[] {
            DataTypes.createStructField("id", DataTypes.StringType, true),
            DataTypes.createStructField("name", DataTypes.StringType, false),
            DataTypes.createStructField("age", DataTypes.IntegerType, false)
       })
    )
    .option("keys.pattern", "person:*")
    .option("key.column", "id")
    .load();

    df.show();
    df.printSchema();     

Output

+----+-----+---+
|  id| name|age|
+----+-----+---+
|null| John| 30|
|null|James| 40|
|null|Peter| 45|
+----+-----+---+

root
    |-- id: string (nullable = true)
    |-- name: string (nullable = false)
    |-- age: integer (nullable = false)

I was expecting 1, 2, 3 respectively in the Id column, but get null instead. Any pointers in this regard will help. Also this code is in Java so I am not sure if there an issue with data types.

When I use IntegerType for the 'Id' field I still get null. When I set nullable parameter to false, I get a NPE for StringType and 0 for IntegerType

**Comment by fe2s** [comment]
I tried to reproduce it, but it works fine for me. I'm using the master branch.
What spark-redis version do you use?

**Comment by jper80** [comment]
I am using spark-redis:2.3.1-M1. 
my pom.xml 
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-core_2.11</artifactId>
			<version>2.3.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-sql_2.11</artifactId>
			<version>2.3.2</version>
		</dependency>
		
		<dependency>
		    <groupId>com.redislabs</groupId>
		    <artifactId>spark-redis</artifactId>
		    <version>2.3.1-M1</version>
		</dependency>

Redis version - 5.0.0

Thanks for the help.

**Comment by jper80** [comment]
I have a java project, need some time figuring out integration with scala projects (spark-redis). Is there a date on next milestone release? I can try that instead if its not too far.

**Comment by gkorland** [comment]
M2 was just released it should be available on the MVN centeral repository soon.
Meanwhile you can get it from the staging 
https://oss.sonatype.org/content/repositories/staging/com/redislabs/spark-redis/2.3.1-M2/

**Comment by jper80** [comment]
Thanks a lot, I don't see this issue on M2.
