### ISSUE TITLE
Intsall Failure

### ISSUE THREAD

**Issue by YYY3000** [RedisLabs/spark-redis#119]
1. download source from https://github.com/RedisLabs/spark-redis/releases
2. mvn install
3. failure
who can help me solve this problem? thanks very much!
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /E:/workplace2/spark-redis-2.3.1-m2/src/test/scala/com/redislabs/provider/redis/util/BenchmarkTest.java:[14,9] 类重复: com.redislabs.provider.redis.uti
l.BenchmarkTest
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 55.738 s
[INFO] Finished at: 2018-11-29T10:52:37+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project spark-redis: Compilation failure

[ERROR] /E:/workplace2/spark-redis-2.3.1-m2/src/test/scala/com/redislabs/provider/redis/util/BenchmarkTest.java:[14,9] 类重复: com.redislabs.provider.redis.uti
l.BenchmarkTest
[ERROR]
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testComp
ile) on project spark-redis: Compilation failure
/E:/workplace2/spark-redis-2.3.1-m2/src/test/scala/com/redislabs/provider/redis/util/BenchmarkTest.java:[14,9] 类重复: com.redislabs.provider.redis.util.Benchm
arkTest

**Comment by fe2s** [comment]
Can you please paste the entire output of maven?

**Comment by YYY3000** [comment]
I have solved this problem.
Just need use mvn install -DskipTests.
Thank you very much for your answer.

**Comment by Jiancong** [comment]
I still met this problem in 2.4.x version. Had to delete all test files depends and make build though.
