### ISSUE TITLE
Can I pass in the server information only when I am writing data?

### ISSUE THREAD

**Issue by cikirt** [RedisLabs/spark-redis#126]
Can I pass in the server information only when I am writing data?
For example:
df.write
        .format("org.apache.spark.sql.redis")
        .option("table", "person")
        .option("key.column", "name")
        .option("spark.redis.host", "localhost")
        .option("spark.redis.port", "5555")
        .save()

The mongo-spark works well:
  ret.write.option("spark.mongodb.output.uri", "")
      .option("spark.mongodb.output.database", "")
      .option("spark.mongodb.output.collection", "")
      .mongo()

**Comment by fe2s** [comment]
Yes, it should be possible with the following parameters (not documented)

```
df.write
.format("org.apache.spark.sql.redis")
.option("table", "person")
.option("key.column", "name")
.option("host", "localhost")
.option("port", "5555")
.save()
```
