### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by Lihengwannafly** [RedisLabs/spark-redis#128]
I didn't first write data into redis via spark-reids, hen I try to use spark-redis to read existing redis data, this error occurs. Should I follow the tutorial first write into redis and then read？
The code is as follows:
```
from pyspark.sql import SparkSession
from pyspark.sql.types import FloatType
from pyspark.sql.types import IntegerType
from pyspark.sql.types import StringType
from pyspark.sql.types import StructField
from pyspark.sql.types import StructType

spark_session = SparkSession \
    .builder \
    .appName("pyspark-read-from-mogno") \
    .config("spark.redis.host", "datanode8") \
    .config("spark.redis.port", 6379) \
    .config("spark.redis.db", 10) \
    .getOrCreate()

schema = StructType([
    StructField("uid", IntegerType(), True),
    StructField("list", StringType(), False),

])
dataframe = spark_session.read.format("org.apache.spark.sql.redis").option("table", "171587_1").option("infer.schema", True).load()
dataframe.printSchema()
dataframe.show()
```

The data in redis is as follows:
```
 keys 171587_1:*
    1) "171587_1:8851003052737506"
    2) "171587_1:01010317121009535188"
    3) "171587_1:8851004159161350"
    4) "171587_1:8851004255182250"
    5) "171587_1:01050518062120206699"
    6) "171587_1:8851003899756552"
    7) "171587_1:8851003052619241"
```

The data type is as follows:
```
127.0.0.1:6379[10]> type 171587_1:8851003052737506
string
```

**Comment by fe2s** [comment]
There is no option to read redis strings into DataFrame. It's only possible to redis hashes or redis strings that were written using spark-redis.

**Comment by Lihengwannafly** [comment]
> There is no option to read redis strings into DataFrame. It's only possible to redis hashes or redis strings that were written using spark-redis.

I got it. Thanks.

**Comment by Lihengwannafly** [comment]
> There is no option to read redis strings into DataFrame. It's only possible to redis hashes or redis strings that were written using spark-redis.

Will spark-redis support read redis strings into Dataframe in the future?

**Comment by fe2s** [comment]
In Python only DataFrames are supported, RDDs are not supported.
There is no plans to read strings into DataFrame at the moment. We may want to revisit it later.

**Comment by Lihengwannafly** [comment]
> In Python only DataFrames are supported, RDDs are not supported.
> There is no plans to read strings into DataFrame at the moment. We may want to revisit it later.

OK, thanks a lot!
