### ISSUE TITLE
sbt cannot resolve jedis dependency

### ISSUE THREAD

**Issue by cedricdeboom** [RedisLabs/spark-redis#134]
It seems as though sbt cannot resolve the current jedis Maven dependency:
https://github.com/RedisLabs/spark-redis/blob/a786380ed47521b5b93af936376a47634be89383/pom.xml#L52

I get:
`[error] coursier.ResolutionException: 1 not found
[error]     https://oss.sonatype.org/content/repositories/snapshots/com/redislabs/jedis/3.0.0-20181113.105826-9/jedis-3.0.0-20181113.105826-9.jar`

I have included the latest 2.3.1-RC1 spark-redis version in the sbt dependencies.
Does someone have an explanation/workaround for me?

**Comment by gkorland** [comment]
http://central.maven.org/maven2/com/redislabs/spark-redis/2.3.1-RC1/spark-redis-2.3.1-RC1-jar-with-dependencies.jar

**Comment by cedricdeboom** [comment]
Thanks for this; I have also been able to build a jar with maven, but not with sbt...

**Comment by igkins** [comment]
What was the resolution for this? I can't build my sbt project either due to this? `"com.redislabs" % "spark-redis" % "2.3.1"`, downgraded to 2.3.0 works though

**Comment by fe2s** [comment]
@igkins please use the workaround from this [comment](https://github.com/RedisLabs/spark-redis/issues/26#issuecomment-480867627)

We will try to fix it in spark-redis 2.4

**Comment by fe2s** [comment]
Fixed in Spark-Redis 2.4.0
