### ISSUE TITLE
Python how to connect to redis cluster ?

### ISSUE THREAD

**Issue by vowers** [RedisLabs/spark-redis#139]
Can I use pyspark redis-spark to connect to redis cluster?
I have a redis cluster
```python
cluster =  [{'host':'10.10.10.34','port':6378},
                    {'host':'10.10.10.34','port':6379},
                    {'host':'10.10.10.35','port':6378},
                    {'host':'10.10.10.35','port':6379},
                    {'host':'10.10.10.36','port':6378},
                    {'host':'10.10.10.36','port':6379},
                    ]
```
and my config:
```python
spark = SparkSession \
        .builder \
        .appName("BasestationsCount") \
        .config("spark.redis.host", "10.10.10.34")\
        .config("spark.redis.port", "6378")\
        .getOrCreate()
loadedDf = spark.read.format("org.apache.spark.sql.redis").option("keys.pattern", "test:*").option("infer.schema", True).load()
```
How to config to  connect to my redis cluster?

**Comment by fe2s** [comment]
You have to specify any node of your cluster in spark configuration, so your code looks to be correct.  Did you try to run it?

**Comment by vowers** [comment]
> You have to specify any node of your cluster in spark configuration, so your code looks to be correct. Did you try to run it?

Yes, I tried to run it and it seems to work properly. Thanks, I just thought I needed to add all the nodes.
