### ISSUE TITLE
Add support for SSL

### ISSUE THREAD

**Issue by alanroche** [RedisLabs/spark-redis#140]
Jedis supports SSL and also via a boolean flag on the JedisPool constructor.
Add an option to configure SSL to true on RedisConfig and propagate to JedisPool.

Tried to prep a Fork/PR for this as it is really simple to fix, but it looks like master does not compile :(
src/test/scala/com/redislabs/provider/redis/util/BenchmarkTest.java:[14,9] duplicate class: com.redislabs.provider.redis.util.BenchmarkTest

**Comment by alanroche** [comment]
Have some changes here: https://github.com/alanroche/spark-redis/commit/fa8288c9230951828b177223bcf59eac09e1309b
Changes are pretty straight forward.
Unfortunately compilation with maven fails,  (  duplicate class: com.redislabs.provider.redis.util.BenchmarkTest ),

@gkorland Let me know if I am doing something obviously wrong

**Comment by benleroux** [comment]
I can see it does not compile still. Any eta? SSL is a key requirement for me.

**Comment by fe2s** [comment]
@benleroux 

the PR #144 seems to compile according to Travis. I haven't tested it yet personally. Could you try it out please?

**Comment by vaggarwal2** [comment]
@alanroche Want to know the status of this PR? I need this feature for my project.

**Comment by fe2s** [comment]
Hi @vaggarwal2 , 
the changes are not tested/verified.

**Comment by rtyler** [comment]
This can now be closed as #235 has been merged

**Comment by fe2s** [comment]
@rtyler thanks!
