### ISSUE TITLE
trying to stream to spark

### ISSUE THREAD

**Issue by AsmaZgo** [RedisLabs/spark-redis#141]
i got the following error 👍 
value createRedisStream is not a member of org.apache.spark.streaming.StreamingContext

for those lignes : 

   val ssc = new org.apache.spark.streaming.StreamingContext(spark.sparkContext, Seconds(1))
val redisStream = ssc.createRedisStream(Array("foo", "bar"),
    storageLevel = StorageLevel.MEMORY_AND_DISK_2)

**Comment by fe2s** [comment]
It looks like you miss the following import:
```
import com.redislabs.provider.redis._
```

**Comment by AsmaZgo** [comment]
yes , i'm sorry for the stupid comment!
