### ISSUE TITLE
Spark 2.4 support?

### ISSUE THREAD

**Issue by kant111** [RedisLabs/spark-redis#147]
Does this work with Spark 2.4? I am specifically interested in `df.writeStream.forEachBatch` and do `MULTI EXEC` within the batch.

**Comment by fe2s** [comment]
spark-redis 2.3.1 should work with spark 2.4, you can find an example of `forEachBatch` in this post https://github.com/RedisLabs/spark-redis/issues/26#issuecomment-475962106

The official spark-redis release that supports 2.4 will come soon.

**Comment by fe2s** [comment]
Spark-Redis 2.4.0 has been released to Maven, so closing this issue.
