### ISSUE TITLE
How to push data(hashes structure) to Redis in Spark Structured Streaming?

### ISSUE THREAD

**Issue by mangrrua** [RedisLabs/spark-redis#157]
I'm using Redis to show latest data to users in web application. For this, I must write data from Spark Structured Streaming to Redis.

I want to save latest data to Redis in **Spark Structured Streaming**. As far as I see, Redis supports **"dataframe write"** to Redis for batch queries. Also, Redis only supports read streaming data **(for pub-sub)** from Redis for Spark Structured streaming.  

But I want to push latest data to Redis. How can I do this?

**Note:** I'm using **Spark 2.3.2**

**Comment by fe2s** [comment]
Hi @mangrrua ,
There is no support for writing from structured streaming to Redis that works with Spark 2.3.2.
With Spark 2.4.x you can leverage `.foreachBatch` function, see the example here https://github.com/RedisLabs/spark-redis/issues/26#issuecomment-475962106

**Comment by mangrrua** [comment]
Yes, I know `.foreachBatch`.  So, I must implement custom Redis Sink for this. Thank you so much!
