### ISSUE TITLE
Overwrites the default CSV reader?

### ISSUE THREAD

**Issue by rien** [RedisLabs/spark-redis#158]
I am trying to use this in my project, but once I add spark-redis as a dependency I am no longer able to read files using the default CSV reader. I get the error:
```
java.lang.ClassNotFoundException: Failed to find data source: org.apache.spark.sql.csv. Please find packages at http://spark.apache.org/third-party-projects.html
```

Does this project overwrite default CSV implementation somehow?

I'm using spark 2.4.0 and tested spark-redis 2.3.1 (from maven) and spark-redis 2.4.0 (from github source).

**Comment by fe2s** [comment]
Hi @rien ,
I have tested `spark.read.csv("...")` and it works fine for me in a standalone application. How do you run your code and how do you declare dependencies?

**Comment by rien** [comment]
I have just tried it again and everything works now. I really have no idea what I did different...

Thank you for the quick response anyway :)
