### ISSUE TITLE
How to make table name dynamic in spark structured streaming

### ISSUE THREAD

**Issue by thedevd** [RedisLabs/spark-redis#164]
I have a spark-structured streaming job which is reading data from two topics say "ABC" and "XYZ".
Topic ABC has data something like - {"id":"1", "name":"Dev", "dept":"IT"} and Topic XYZ has data something like- {"id":"12", "name":"Devika", "dept":"SALES"}
And I am aggregating them based on a column "dept".  So what I want that data of topic ABC should go to redis table "IT" (based on its dept value) and data from XYZ topic should go to redis table "SALES". 

Note I want to do this in same write query. So how to do this -->

my code is like - 

    val aggregatedDF= ....

    val query = aggregatedDF
      .writeStream
      .outputMode("update")
      .foreachBatch { (batchDF: DataFrame, batchId: Long) =>
          batchDF
          .select("id","name","dept").as("data")
          .selectExpr("CAST(id AS STRING) AS key", "CAST(data AS STRING) AS value")
          .write
          .format("org.apache.spark.sql.redis")
          .option("table", "yourTableName") // ## This is I want to create dynimcally
          .option("key.column", "id")
          .mode(SaveMode.Append)
          .save()
      }
      .start()

**Comment by fe2s** [comment]
Hi @thedevd ,

I don't think it's possible to dynamically set "table" option. But in essence the "table" option only controls the prefix of the key in Redis, i.e. the key is "$table:$key.column". So If I understand your use case correctly, you can create a new column as a concatenation of "dept" and the rest of you aggregation key (is it "id" column?) and use it as a "key.column", e.g.
```
batchDF.
withColumn('key', batchDF.concat(batchDF.col('dept'),batchDF.lit(':'), batchDF.col('id')))
.write
      .format("org.apache.spark.sql.redis")
      .option("table", "yourTableName") 
      .option("key.column", "key")
      .mode(SaveMode.Append)
      .save()
```
After that your key should look like "yourTableName:$dept:$id". And then you can access data for different dept with the prefix "yourTableName:$dept:*"

**Comment by thedevd** [comment]
@fe2s Yes you understood it very right. Now I have done the same, I created the key by concatenating dept and id using colon, And I believe this is going to solve it :) 

      val aggregatedDF= ....

      val query = aggregatedDF
      .writeStream
      .outputMode("update")
      .foreachBatch { (batchDF: DataFrame, batchId: Long) =>
      batchDF
      .select(concat_ws(":","dept","id").as("key"), 
         to_json(struct("id","name","dept")).as("value"))
      .selectExpr("CAST(key AS STRING)", "CAST(value AS STRING)")
      .write
      .format("org.apache.spark.sql.redis")
      .option("table", "empdetailsbydept") 
      .option("key.column", "key") // concatinated key here dept:id
      .mode(SaveMode.Append)
      .save()
  }
  .start()

**Comment by thedevd** [comment]
@fe2s ,
I am running into another problem. Now I have the data in redis in the form of nested keys such as -
dept:id --> value. After making it more nested like universityName:dept:id ---> value, I am not sure how to create  readstream to read all those value in structured streaming. 

This is how I have list of keys in redis and each having value -
"oxford:Finance:1134081"
"oxford:Finance:3936513"
"oxford:Finance:3486721"
"oxford:Research:5202689"
"oxford:Research:2921217"
"oxford:Research:7578881"
"oxford:Science:259593"
"oxford:Science:850945"

So what I want now to read all the values for keys starting with oxford -
      val deptEmp= spark
      .readStream
      .format("redis")                          // read from Redis
      .option("stream.keys", "oxford*:*")

this gives me below given exception -

**Comment by fe2s** [comment]
Are you trying to read Redis strings into a Structured Stream? This is not possible. You can only use Spark Structured Streaming with Redis Stream. If you'd like to read Redis strings - you can do with Spark-Redis RDD support. 

As for your exception - it looks like you are not running Redis 5.0.0 or higher and it doesn't support 'xgroup' command.

**Comment by thedevd** [comment]
@fe2s ,

This is how I have written my data into redis - 

      // This is for redis sink
    val writeToRedis = aggregates
      .writeStream
      .trigger(Trigger.ProcessingTime(60.seconds))
      .outputMode(OutputMode.Update)
      .foreachBatch { (batchDF: DataFrame, batchId: Long) =>
        batchDF
          .select(concat_ws(":",$"deptName",$"id").as("key"),
           to_json(struct("id","name","age","salary")).as("value"))
          .selectExpr("CAST(key AS STRING)", "CAST(value AS STRING)")
          .write
          .format("org.apache.spark.sql.redis")
          .option("table",  "oxford")
          .option("key.column", "key")
          .mode(SaveMode.Append)
          .save()
      }
      .start()


So you are saying it is not possible to open readStream to read all keys created above in structured streaming, but my problem statement is that I want to stream those keys continuously and save them in another permanent sink like MySQL using JDBC.
 Could you please guide me.

**Comment by fe2s** [comment]
If you'd like to create a pipleine like this
Input -> Spark Stream -> Redis -> Spark Stream -> MySQL
why do you need to store intermediate results in Redis at all? Can you just do the following?
Input -> Spark Stream -> MySQL

**Comment by thedevd** [comment]
@fe2s 
As other jobs in the application need that intermediate data to do further real-time processing. So I am storing the data in Redis for faster access whenever needed.

**Comment by fe2s** [comment]
It sounds like you might need to output the Structured Streaming result back to another Redis Stream. Right? There is no built-in support for that at the moment in Spark-Redis.
