### ISSUE TITLE
Can I query or store data to spark-redis via JDBC driver, hive-thriftserver ?

### ISSUE THREAD

**Issue by jclee81** [RedisLabs/spark-redis#17]
As spark-redis documents, spark-redis supports spark-sql as well as dataframe, but I can't find any codes in the repo. My consideration is that I'd like to store data with a specific scheme to redis and retrieve them using JDBC API like SQL statement.

**Comment by sunheehnus** [comment]
Hello @jclee81 , sorry the spark-sql is not currently implemented, but it is in plan. The API for users is not very clear currently, do you have any suggestions? Thanks

**Comment by iwaniwaniwan012** [comment]
Is it working now? I tried to use it with spark 2.2.0 but got error "Error: java.lang.NoClassDefFoundError: org/apache/spark/sql/DataFrame (state=,code=0)" in "spark beeline"

**Comment by gkorland** [comment]
See #32
