### ISSUE TITLE
Is it possible to do "FLUSHDB" using the Python Spark-redis API?

### ISSUE THREAD

**Issue by aizest** [RedisLabs/spark-redis#171]
It's too slow to update the existing entries in a database, using the "overwrite" mode.
For example, use the following code:

df.write.format("org.apache.spark.sql.redis").option("table", "db1").option("key.column", "uid").option("host", REDIS_HOST).option("port", REDIS_PORT).option("auth", REDIS_PW).mode("overwrite").save()

Could we remove all the keys in a DB with the Python API?
I don't want to append records to existing keys in a database.

Thanks!

**Comment by fe2s** [comment]
It's not possible out of the box. It might be possible to access `jedis` connection in java/scala and then wrap it with Py4J (python-java library used by PySpark), but I didn't try that.

With `overwrite` mode it first has to read all the keys in the dataframe and then execute `del` for command for each of them. 

Is it a single redis node or cluster? 
How many spark executors?
How many keys do you insert and how long does it take for you?

**Comment by aizest** [comment]
Thanks for the quick response.

Is there any related tutorials on how to implement FLUSHDB using jedis?

Right now we're using a single Redis node, which may be extended to a 3-node cluster.
We have up to 400 spark executors.

Right now, we have about 12M keys in the existing Redis database. 
The writing operation can't finish in 5 minutes when I tried to write just 100 new key-values to that DB under the "overwrite" mode.
In the future, we may write 15M to 25 M key-values everyday. 
That's why we want to clean up the database before writing new values.

**Comment by fe2s** [comment]
Actually it might be easier to just use python's client for Redis rather than trying to execute Java method in Python. Here is an example https://stackoverflow.com/questions/45916183/how-do-i-to-flush-redis-db-from-python-redis

Internally it has to `SCAN` 12M keys and then `DEL` those that belong to the dataframe in order to implement `overwrite` mode. Unfortunately there seems to be no better way. That's why it take a lot of time.

**Comment by aizest** [comment]
Thanks a lot. The redis-py API has worked very well so far. Appreciate the valuable help!
