### ISSUE TITLE
It does not work in Amazon EMR（spark2.4.0, redis2.9.0）？

### ISSUE THREAD

**Issue by JWenBin** [RedisLabs/spark-redis#172]
**It works when I use "{Jedis, JedisPool, JedisPoolConfig}"**
scala> 	   import redis.clients.jedis.{Jedis, JedisPool, JedisPoolConfig}
scala>     val pool=new JedisPool(config,"172.7.30.219",7002,10000) //连接池
pool: redis.clients.jedis.JedisPool = redis.clients.jedis.JedisPool@cd7df73

scala>  val jr: Jedis = pool.getResource
jr: redis.clients.jedis.Jedis = redis.clients.jedis.Jedis@1c2d64

scala>     jr.get("123")
res24: String = test123

**But it doesn't works when I use "com.redislabs.provider.redis._"**
scala> spark.conf.set("redis.host", "172.7.30.219") 

scala> spark.conf.set("redis.port", 7002)

scala> val keysRDD = sc.fromRedisKeyPattern("foo*", 5)
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
  at redis.clients.util.Pool.getResource(Pool.java:53)
  at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
  at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
  at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:69)
  at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:182)
  at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:293)
  at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:209)
  at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:132)
  at com.redislabs.provider.redis.RedisConfig$.fromSparkConf(RedisConfig.scala:120)
  at com.redislabs.provider.redis.RedisContext.fromRedisKeyPattern$default$3(redisFunctions.scala:27)
  ... 51 elided
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
  at redis.clients.jedis.Connection.connect(Connection.java:207)
  at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
  at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
  at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
  at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
  at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
  at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
  at redis.clients.util.Pool.getResource(Pool.java:49)
  ... 60 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:589)
  at redis.clients.jedis.Connection.connect(Connection.java:184)
  ... 67 more

**Comment by fe2s** [comment]
The confit parameters should be prefixed with “spark”, eg “spark.redis.host”. Also not sure if you can configure it with spark.conf.set in a shell. Please see here https://github.com/RedisLabs/spark-redis/blob/master/doc/getting-started.md how to pass configuration parameters as command line args to spark-shell

**Comment by JWenBin** [comment]
**I tried it as you said, but still fail.**

scala>     val pool=new JedisPool(config,"172.17.30.219",7003,10000) //连接池
pool: redis.clients.jedis.JedisPool = redis.clients.jedis.JedisPool@2dedf1c9

scala>   val jr: Jedis = pool.getResource 
jr: redis.clients.jedis.Jedis = redis.clients.jedis.Jedis@5cd8bf01

scala> jr.get("jutil")
res12: String = test123

scala> spark.conf.set("spark.redis.host", "172.17.30.29") 

scala> spark.conf.set("spark.redis.port", 7003)

scala> val sc=spark.sparkContext
sc: org.apache.spark.SparkContext = org.apache.spark.SparkContext@568945a9

scala> val stringRDD = sc.fromRedisKV("test")
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
  at redis.clients.util.Pool.getResource(Pool.java:53)
  at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
  at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
  at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:69)
  at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:182)
  at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:293)
  at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:209)
  at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:132)
  at com.redislabs.provider.redis.RedisConfig$.fromSparkConf(RedisConfig.scala:120)
  at com.redislabs.provider.redis.RedisContext.fromRedisKV$default$3(redisFunctions.scala:55)
  ... 51 elided
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
  at redis.clients.jedis.Connection.connect(Connection.java:207)
  at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
  at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
  at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
  at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
  at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
  at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
  at redis.clients.util.Pool.getResource(Pool.java:49)
  ... 60 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:589)
  at redis.clients.jedis.Connection.connect(Connection.java:184)
  ... 67 more

scala>

**Comment by fe2s** [comment]
You have to start the spark-shell with the proper command line args. Please see the link in my previous answer.

**Comment by liuxiaoji** [comment]
I have the same problem, but my version is 2.3.0,
$ spark-shell --packages com.redislabs:spark-redis:2.3.0 --conf "spark.redis.host=myhost" --conf "spark.redis.port=6379" --conf "spark.redis.auth=password"
>import com.redislabs.provider.redis._
val ii = sc.fromRedisKV("USER_INFO_A932D972162879CD4DC273E439584E9C")
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
  at redis.clients.util.Pool.getResource(Pool.java:53)
  at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
  at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
  at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:67)
  at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:139)
  at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:250)
  at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:166)
  at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:89)
  at com.redislabs.provider.redis.RedisContext.fromRedisKV$default$3(redisFunctions.scala:51)
  ... 51 elided
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
  at redis.clients.jedis.Connection.connect(Connection.java:207)
  at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
  at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
  at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
  at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
  at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
  at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
  at redis.clients.util.Pool.getResource(Pool.java:49)
  ... 59 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
  at java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:589)
  at redis.clients.jedis.Connection.connect(Connection.java:184)
  ... 66 more
>  import redis.clients.jedis.Jedis
>val jedisCli = new Jedis("myhost", 6379);
>jediscli.auth("password")
>jedisCli.get("USER_INFO_A932D972162879CD4DC273E439584E9C")
res4: ......

**Comment by JWenBin** [comment]
> 
> 
> I have the same problem, but my version is 2.3.0,
> $ spark-shell --packages com.redislabs:spark-redis:2.3.0 --conf "spark.redis.host=myhost" --conf "spark.redis.port=6379" --conf "spark.redis.auth=password"
> 
> > import com.redislabs.provider.redis._
> > val ii = sc.fromRedisKV("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
> > at redis.clients.util.Pool.getResource(Pool.java:53)
> > at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
> > at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
> > at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:67)
> > at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:139)
> > at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:250)
> > at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:166)
> > at com.redislabs.provider.redis.RedisConfig.(RedisConfig.scala:89)
> > at com.redislabs.provider.redis.RedisContext.fromRedisKV$default$3(redisFunctions.scala:51)
> > ... 51 elided
> > Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
> > at redis.clients.jedis.Connection.connect(Connection.java:207)
> > at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
> > at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
> > at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
> > at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
> > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
> > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
> > at redis.clients.util.Pool.getResource(Pool.java:49)
> > ... 59 more
> > Caused by: java.net.ConnectException: Connection refused (Connection refused)
> > at java.net.PlainSocketImpl.socketConnect(Native Method)
> > at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> > at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> > at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> > at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> > at java.net.Socket.connect(Socket.java:589)
> > at redis.clients.jedis.Connection.connect(Connection.java:184)
> > ... 66 more
> > import redis.clients.jedis.Jedis
> > val jedisCli = new Jedis("myhost", 6379);
> > jediscli.auth("password")
> > jedisCli.get("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > res4: ......

你咋带着“ --packages com.redislabs:spark-redis:2.3.0  ” ？我本地windows10上运行没事，就是服务器上不行

**Comment by liuxiaoji** [comment]
> > I have the same problem, but my version is 2.3.0,
> > $ spark-shell --packages com.redislabs:spark-redis:2.3.0 --conf "spark.redis.host=myhost" --conf "spark.redis.port=6379" --conf "spark.redis.auth=password"
> > > import com.redislabs.provider.redis._
> > > val ii = sc.fromRedisKV("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > > redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
> > > at redis.clients.util.Pool.getResource(Pool.java:53)
> > > at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
> > > at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
> > > at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:67)
> > > at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:139)
> > > at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:250)
> > > at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:166)
> > > at com.redislabs.provider.redis.RedisConfig.(RedisConfig.scala:89)
> > > at com.redislabs.provider.redis.RedisContext.fromRedisKV$default$3(redisFunctions.scala:51)
> > > ... 51 elided
> > > Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
> > > at redis.clients.jedis.Connection.connect(Connection.java:207)
> > > at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
> > > at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
> > > at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
> > > at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
> > > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
> > > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
> > > at redis.clients.util.Pool.getResource(Pool.java:49)
> > > ... 59 more
> > > Caused by: java.net.ConnectException: Connection refused (Connection refused)
> > > at java.net.PlainSocketImpl.socketConnect(Native Method)
> > > at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> > > at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> > > at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> > > at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> > > at java.net.Socket.connect(Socket.java:589)
> > > at redis.clients.jedis.Connection.connect(Connection.java:184)
> > > ... 66 more
> > > import redis.clients.jedis.Jedis
> > > val jedisCli = new Jedis("myhost", 6379);
> > > jediscli.auth("password")
> > > jedisCli.get("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > > res4: ......
> 
> 你咋带着“ --packages com.redislabs:spark-redis:2.3.0 ” ？我本地windows10上运行没事，就是服务器上不行

我在服务器上面执行的，spark-shell 配置packages下载需要的包引入，服务器是阿里云ecs,redis也是阿里云的redis实例，

**Comment by JWenBin** [comment]
**Thank you all, I tried it again and success！**

[hadoop@ip-172-17-4-8 ~]$ spark-shell --master local[1] --driver-memory 1G --jars s3://jars/spark-redis-2.4.0.jar --conf "spark.redis.host=172.17.30.29" --conf "spark.redis.port=7000" 
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
19/05/31 08:10:28 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/05/31 08:10:28 WARN SparkContext: The jar s3://boomplay/EMR/jars/spark-redis-2.4.0.jar has been added already. Overwriting of added jars is not supported in the current version.
Spark context Web UI available at http://ip-172-17-4-8.eu-west-1.compute.internal:4041
Spark context available as 'sc' (master = local[1], app id = local-1559290228730).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.0
      /_/
         
Using Scala version 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_191)
Type in expressions to have them evaluated.
Type :help for more information.

scala> spark.conf.get("spark.redis.host")
res0: String = 172.17.30.29

scala> spark.conf.get("spark.redis.port")
res1: String = 7000

scala> val sc=spark.sparkContext
sc: org.apache.spark.SparkContext = org.apache.spark.SparkContext@ff7042c

scala>  import com.redislabs.provider.redis._
import com.redislabs.provider.redis._

scala> val stringRDD = sc.fromRedisKV("jutil")
stringRDD: org.apache.spark.rdd.RDD[(String, String)] = RedisKVRDD[3] at RDD at RedisRDD.scala:20

scala> println(stringRDD)
RedisKVRDD[3] at RDD at RedisRDD.scala:20

scala> stringRDD.collect.foreach(print)
(jutil,test123) 

注：这是亚马逊emr集群

**Comment by JWenBin** [comment]
> 
> 
> > > I have the same problem, but my version is 2.3.0,
> > > $ spark-shell --packages com.redislabs:spark-redis:2.3.0 --conf "spark.redis.host=myhost" --conf "spark.redis.port=6379" --conf "spark.redis.auth=password"
> > > > import com.redislabs.provider.redis._
> > > > val ii = sc.fromRedisKV("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > > > redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
> > > > at redis.clients.util.Pool.getResource(Pool.java:53)
> > > > at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
> > > > at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
> > > > at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:67)
> > > > at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:139)
> > > > at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:250)
> > > > at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:166)
> > > > at com.redislabs.provider.redis.RedisConfig.(RedisConfig.scala:89)
> > > > at com.redislabs.provider.redis.RedisContext.fromRedisKV$default$3(redisFunctions.scala:51)
> > > > ... 51 elided
> > > > Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
> > > > at redis.clients.jedis.Connection.connect(Connection.java:207)
> > > > at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
> > > > at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
> > > > at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
> > > > at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
> > > > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
> > > > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
> > > > at redis.clients.util.Pool.getResource(Pool.java:49)
> > > > ... 59 more
> > > > Caused by: java.net.ConnectException: Connection refused (Connection refused)
> > > > at java.net.PlainSocketImpl.socketConnect(Native Method)
> > > > at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> > > > at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> > > > at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> > > > at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> > > > at java.net.Socket.connect(Socket.java:589)
> > > > at redis.clients.jedis.Connection.connect(Connection.java:184)
> > > > ... 66 more
> > > > import redis.clients.jedis.Jedis
> > > > val jedisCli = new Jedis("myhost", 6379);
> > > > jediscli.auth("password")
> > > > jedisCli.get("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > > > res4: ......
> > 
> > 
> > 你咋带着“ --packages com.redislabs:spark-redis:2.3.0 ” ？我本地windows10上运行没事，就是服务器上不行
> 
> 我在服务器上面执行的，spark-shell 配置packages下载需要的包引入，服务器是阿里云ecs,redis也是阿里云的redis实例，

我按你写的，，，，运行连接成功了o(╯□╰)o

**Comment by liuxiaoji** [comment]
> > > > I have the same problem, but my version is 2.3.0,
> > > > $ spark-shell --packages com.redislabs:spark-redis:2.3.0 --conf "spark.redis.host=myhost" --conf "spark.redis.port=6379" --conf "spark.redis.auth=password"
> > > > > import com.redislabs.provider.redis._
> > > > > val ii = sc.fromRedisKV("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > > > > redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
> > > > > at redis.clients.util.Pool.getResource(Pool.java:53)
> > > > > at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
> > > > > at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
> > > > > at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:67)
> > > > > at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:139)
> > > > > at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:250)
> > > > > at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:166)
> > > > > at com.redislabs.provider.redis.RedisConfig.(RedisConfig.scala:89)
> > > > > at com.redislabs.provider.redis.RedisContext.fromRedisKV$default$3(redisFunctions.scala:51)
> > > > > ... 51 elided
> > > > > Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
> > > > > at redis.clients.jedis.Connection.connect(Connection.java:207)
> > > > > at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
> > > > > at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
> > > > > at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
> > > > > at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
> > > > > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
> > > > > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
> > > > > at redis.clients.util.Pool.getResource(Pool.java:49)
> > > > > ... 59 more
> > > > > Caused by: java.net.ConnectException: Connection refused (Connection refused)
> > > > > at java.net.PlainSocketImpl.socketConnect(Native Method)
> > > > > at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> > > > > at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> > > > > at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> > > > > at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> > > > > at java.net.Socket.connect(Socket.java:589)
> > > > > at redis.clients.jedis.Connection.connect(Connection.java:184)
> > > > > ... 66 more
> > > > > import redis.clients.jedis.Jedis
> > > > > val jedisCli = new Jedis("myhost", 6379);
> > > > > jediscli.auth("password")
> > > > > jedisCli.get("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > > > > res4: ......
> > > 
> > > 
> > > 你咋带着“ --packages com.redislabs:spark-redis:2.3.0 ” ？我本地windows10上运行没事，就是服务器上不行
> > 
> > 
> > 我在服务器上面执行的，spark-shell 配置packages下载需要的包引入，服务器是阿里云ecs,redis也是阿里云的redis实例，
> 
> 我按你写的，，，，运行连接成功了o(╯□╰)o

我再检查检查，看看是不是机器的问题

**Comment by liuxiaoji** [comment]
> > > > I have the same problem, but my version is 2.3.0,
> > > > $ spark-shell --packages com.redislabs:spark-redis:2.3.0 --conf "spark.redis.host=myhost" --conf "spark.redis.port=6379" --conf "spark.redis.auth=password"
> > > > > import com.redislabs.provider.redis._
> > > > > val ii = sc.fromRedisKV("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > > > > redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
> > > > > at redis.clients.util.Pool.getResource(Pool.java:53)
> > > > > at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
> > > > > at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:33)
> > > > > at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:67)
> > > > > at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:139)
> > > > > at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:250)
> > > > > at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:166)
> > > > > at com.redislabs.provider.redis.RedisConfig.(RedisConfig.scala:89)
> > > > > at com.redislabs.provider.redis.RedisContext.fromRedisKV$default$3(redisFunctions.scala:51)
> > > > > ... 51 elided
> > > > > Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
> > > > > at redis.clients.jedis.Connection.connect(Connection.java:207)
> > > > > at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
> > > > > at redis.clients.jedis.BinaryJedis.connect(BinaryJedis.java:1767)
> > > > > at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:106)
> > > > > at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:819)
> > > > > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:429)
> > > > > at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:360)
> > > > > at redis.clients.util.Pool.getResource(Pool.java:49)
> > > > > ... 59 more
> > > > > Caused by: java.net.ConnectException: Connection refused (Connection refused)
> > > > > at java.net.PlainSocketImpl.socketConnect(Native Method)
> > > > > at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> > > > > at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> > > > > at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> > > > > at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> > > > > at java.net.Socket.connect(Socket.java:589)
> > > > > at redis.clients.jedis.Connection.connect(Connection.java:184)
> > > > > ... 66 more
> > > > > import redis.clients.jedis.Jedis
> > > > > val jedisCli = new Jedis("myhost", 6379);
> > > > > jediscli.auth("password")
> > > > > jedisCli.get("USER_INFO_A932D972162879CD4DC273E439584E9C")
> > > > > res4: ......
> > > 
> > > 
> > > 你咋带着“ --packages com.redislabs:spark-redis:2.3.0 ” ？我本地windows10上运行没事，就是服务器上不行
> > 
> > 
> > 我在服务器上面执行的，spark-shell 配置packages下载需要的包引入，服务器是阿里云ecs,redis也是阿里云的redis实例，
> 
> 我按你写的，，，，运行连接成功了o(╯□╰)o

我的问题也解决了， 下午看了下源码，在2.3里面获取配置的源码是这样的：
case class RedisEndpoint(val host: String = Protocol.DEFAULT_HOST,
                         val port: Int = Protocol.DEFAULT_PORT,
                         val auth: String = null,
                         val dbNum: Int = Protocol.DEFAULT_DATABASE,
                         val timeout: Int = Protocol.DEFAULT_TIMEOUT)
  extends Serializable {

  /**
    * Constructor from spark config. set params with redis.host, redis.port, redis.auth and redis.db
    *
    * @param conf spark context config
    */
  def this(conf: SparkConf) {
      this(
        conf.get("redis.host", Protocol.DEFAULT_HOST),
        conf.getInt("redis.port", Protocol.DEFAULT_PORT),
        conf.get("redis.auth", null),
        conf.getInt("redis.db", Protocol.DEFAULT_DATABASE),
        conf.getInt("redis.timeout", Protocol.DEFAULT_TIMEOUT)
      )
  }
所以我的配置有问题，2.4的源码我没看，你可以确认下，在RedisConfig.scala中

**Comment by liuxiaoji** [comment]
My problem has been solved because the configuration name of redis in version 2.3 is not quite the same as in the example
