### ISSUE TITLE
Can you add support for Map<byte[], byte[]> hgetAll(final byte[] key) method operations

### ISSUE THREAD

**Issue by chenjunfeng001** [RedisLabs/spark-redis#175]
Redis stores the data in the protobuf format and retrieves the byte array type

**Comment by fe2s** [comment]
@chenjunfeng001 can you query hashes using `sc.fromRedisHash()`, then `map` rdd with a `String.getBytes` and deserialize the protobuf from there? Or do you expect some major performance issues because of the extra string->bytes conversion?

**Comment by chenjunfeng001** [comment]
@fe2s Thank you！`String.getbytes` doesn't solve the special character case, so for now it's base64！The code is as follows: `byte[] decode = Base64.getDecoder().decode(tuple2._2);
                       DimIndicator.DimPendsettle dimPendsettle = DimIndicator.DimPendsettle.parseFrom(decode);
                       String dimPendsettleStr = JsonFormat.printer().print(dimPendsettle);`
