### ISSUE TITLE
fromRedisKeyPattern error

### ISSUE THREAD

**Issue by Ts686** [RedisLabs/spark-redis#192]
![image](https://user-images.githubusercontent.com/30523983/63152294-138ca300-c03e-11e9-876f-188753d95c06.png)
Anybody come across that ?

**Comment by fe2s** [comment]
Hi @Ts686 ,
please make sure there is a correct version of jedis in your classpath.

**Comment by Ts686** [comment]
> Hi @Ts686 ,
> please make sure there is a correct version of jedis in your classpath.

Yes, I used the wrong version. Thank you very much
