### ISSUE TITLE
Support Scala2.12+ 

### ISSUE THREAD

**Issue by 2efPer** [RedisLabs/spark-redis#193]
Can we support scala2.12+?

**Comment by fe2s** [comment]
I added scala 2.12 build support in this [branch](https://github.com/RedisLabs/spark-redis/tree/build_scala_2.12)

You can build using `scala-2.12` profile:  
```
mvn -P scala-2.12 clean package -DskipTests
```
or with make:
```
make package MVN_EXTRA_OPTS="-P scala-2.12"
```

Also changed Travis script to run tests both for scala 2.11 (default version in pom.xml) an for scala 2.12.

The artifacts are not yet published to Maven central, I will ask @gkorland to deploy it.

**Comment by fe2s** [comment]
It seems like the approach of using maven profiles for cross compiling different scala versions doesn't work.
I tested the published Sonatype artifact and getting error both with sbt and maven.

SBT error:
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.redislabs#spark-redis_2.12;2.4.1-SNAPSHOT: java.text.ParseException: inconsistent module descriptor file found in 'https://oss.sonatype.org/content/repositories/snapshots/com/redislabs/spark-redis_2.12/2.4.1-SNAPSHOT/spark-redis_2.12-2.4.1-20190909.083112-1.pom': bad module name: expected='spark-redis_2.12' found='spark-redis_2.11';
```   

Typically SBT used for cross compiling and it appears to be not very common with maven.

We may want to consider the following appraoches:
* using maven plugin https://github.com/Stratio/scala-cross-build-maven-plugin
* script to replace scala version in pom file, similar to Spark project, https://spark.apache.org/docs/latest/building-spark.html#change-scala-version

**Comment by anton-antonenko** [comment]
Hey!
Are you going to fix it in the next release? And if so, when it's planned to come?

**Comment by fe2s** [comment]
Hi Anton,
No estimates for this yet.

**Comment by anton-antonenko** [comment]
Ok, np 🙂
Thanks for the quick response

**Comment by menykobel** [comment]
Hi,
Since spark-redis connector doesn't support scala 2.12+ I cant upgrade to new spark version 2.4.5 (spark 2.4.5 runs on Scala 2.12+).
Appreciate if you could publish new version.

**Comment by gkorland** [comment]
> Hi,
> Since spark-redis connector doesn't support scala 2.12+ I cant upgrade to new spark version 2.4.5 (spark 2.4.5 runs on Scala 2.12+).
> Appreciate if you could publish new version.

**Comment by fe2s** [comment]
2.11 and 2.12 artifacts have been published to Maven

https://search.maven.org/artifact/com.redislabs/spark-redis_2.11
https://search.maven.org/artifact/com.redislabs/spark-redis_2.12
