### ISSUE TITLE
Is there any explanation of "avoiding using db number"?

### ISSUE THREAD

**Issue by misssprite** [RedisLabs/spark-redis#20]
My business logic need to batch update records.
My solution is to write to another db and switch to that db, hoping to reduce down time of the redis service.
Or is there better solution?

**Comment by sunheehnus** [comment]
Hello @misssprite , db number is not supported in Redis Cluster, if you are using a standalone redis instance, you can use it.

**Comment by misssprite** [comment]
So is the support for cluster scheduled or does it conflict with cluster mode?

**Comment by sunheehnus** [comment]
As Redis Cluster doesn't support `db number`, it is not scheduled :-)

**Comment by misssprite** [comment]
Thank you! @sunheehnus
