### ISSUE TITLE
Is there a way to pass the Redis credentials to the write and read function instead of the Spark session?

### ISSUE THREAD

**Issue by argenisleon** [RedisLabs/spark-redis#206]
Hi,

Instead of passing the Redis credential in the spark session creation moment, Is it possible to pass the info at reading or writing time?

Something like:
```
conf = df.write \
            .option("url", self.url) \
            .option("user", self.user) \
            .option("password", self.password).save()
```

**Comment by fe2s** [comment]
Hi @argenisleon ,
Yes, it's possible. The parameter names are "host", "port", "auth", "dbNum", "timeout".
"auth" is a password.

**Comment by fe2s** [comment]
The related source code https://github.com/RedisLabs/spark-redis/blob/master/src/main/scala/org/apache/spark/sql/redis/RedisSourceRelation.scala#L43
