### ISSUE TITLE
Will the streaming get the data in Redis which is pushed before streaming start?

### ISSUE THREAD

**Issue by Litchilitchy** [RedisLabs/spark-redis#209]
Ideally we want to use streaming to process all data in Redis, in a streaming manner, thus I suppose we are using Output Mode of Append. And we start the streaming job first, push data into Redis, the streaming will continuously get the new data.

However, if my streaming job want to shut down somehow, and at the same time I want to keep the Redis running, so data could still be pushed to Redis and I want to process them after next time I run the streaming job.

However, can this work? Theoretically the streaming job will only get the data appended to Redis after the job starts? So if I am doing something like, push 1, start streaming, push 2. Then it would only get 2?

**Comment by fe2s** [comment]
Hi @Litchilitchy ,

Please see this doc https://github.com/RedisLabs/spark-redis/blob/master/doc/structured-streaming.md#stream-offset . If you'd like to process all the stream data starting from beginning, set offset id to `0-0`.

**Comment by Litchilitchy** [comment]
Hi @fe2s , in your docs it says "the latest stream in Redis". How do you define this?

1)The latest stream arrives Redis since this spark job starts? 2)Or the Redis streaming has a internal index defining "latest"?

I am wondering if spark-redis could achieve the similar feature of the `nc -lk 9999` example in Spark doc, that if you send messages as [send 1, stop spark job, send 2,3,4, start spark job], the streaming will get all of [2,3,4] after it starts, although they are sent during no spark structured streaming running. 

It seems more like 2) above. Could you kindly tell the behavior and overall implementation about this?

**Comment by fe2s** [comment]
`msg1, msg2, spark started, msg3, msg4, msg5`
By default, it will consume: `msg3, msg4, msg5`. If you'd like to start from the specific offset, you can configure `stream.offset` parameter as I wrote above.

If the job is stopped and started again later, no messages should be lost:
`msg1, msg2, spark started, msg3, msg4, msg5, spark stopped, msg6, msg7, spark started, msg8`
It will consume: `msg3, msg4, msg5, msg6, msg7, msg8`.

**Comment by Litchilitchy** [comment]
@fe2s  So basically spark-redis creates a redis group when spark starts, and **maintain an offset in Redis**, so after it first starts, the start and stop of spark would use this offset and no data would be lost?

**Comment by fe2s** [comment]
@Litchilitchy correct

**Comment by Litchilitchy** [comment]
@fe2s Thanks for your explanation! Closed.
