### ISSUE TITLE
can I switch DB in one Spark Job?

### ISSUE THREAD

**Issue by smokeriu** [RedisLabs/spark-redis#212]
Hello!
I'm using standalone redis.
My Spark Job need to access 3 different DBs.
After some testing , I still don't know how  to do this.
So can I access different DBs in one Spark job?
Thanks.

**Comment by fe2s** [comment]
Hi @smokeriu ,
What kind of API do you use? RDD, DataFrames, streaming or structured streaming?

**Comment by smokeriu** [comment]
> Hi @smokeriu ,
> What kind of API do you use? RDD, DataFrames, streaming or structured streaming?

Most of the time I do this in DataFrame.
If possible, please also tell me how to do it in SparkStreaming.
Thanks.

**Comment by fe2s** [comment]
You can change the connection settings using dataframe options: `host`, `port`, `auth`
For example:

```scala
df.write
      .format("org.apache.spark.sql.redis")
      .option("host", "localhost")
      .option("port", "6379")
      .option("table", "person")
      .save()
```

These options are not listed in the documentation, we will need to document it.

As for Spark Streaming(DStreams), the API functions accept an implicit parameter `RedisConfig`:

```scala
val redisConfig = new RedisConfig(RedisEndpoint(host = "localhost", port = 6379))
val stream = ssc.createRedisXStream(Seq(ConsumerConfig(streamKey, "g1", "c1", Earliest)), StorageLevel.MEMORY_ONLY)(redisConfig)
```

**Comment by smokeriu** [comment]
> You can change the connection settings using dataframe options: `host`, `port`, `auth`
> For example:
> 
> ```scala
> df.write
>       .format("org.apache.spark.sql.redis")
>       .option("host", "localhost")
>       .option("port", "6379")
>       .option("table", "person")
>       .save()
> ```
> 
> These options are not listed in the documentation, we will need to document it.
> 
> As for Spark Streaming(DStreams), the API functions accept an implicit parameter `RedisConfig`:
> 
> ```scala
> val redisConfig = new RedisConfig(RedisEndpoint(host = "localhost", port = 6379))
> val stream = ssc.createRedisXStream(Seq(ConsumerConfig(streamKey, "g1", "c1", Earliest)), StorageLevel.MEMORY_ONLY)(redisConfig)
> ```
Thank you for your help, I know how to change host and port when I write DataFrame  to Redis.

But my redis is in standalone mode,unlike cluster.
These option don't seem to help me to select db.
Like:
I can do this in sparksession:(_This can help me to select db.But once I have created sparksession, I cannot change the connection by modifying Sparkconf_)
```
SparkSession.builder().config("spark.redis.db",3)
```
or in redis-cli:
```
xxx:6379>select 3
```

In addition, these options don't seem to work in read mode(DataFrame.read)?

**Comment by fe2s** [comment]
It's `dbNum` option, e.g.

```scala
df.write
      .format("org.apache.spark.sql.redis")
      .option("dbNum", "3")
      .option("table", "person")
      .save()
```

**Comment by smokeriu** [comment]
> It's `dbNum` option, e.g.
> 
> ```scala
> df.write
>       .format("org.apache.spark.sql.redis")
>       .option("dbNum", "3")
>       .option("table", "person")
>       .save()
> ```

I just found it in 
```
org.apache.spark.sql.redis.RedisSourceRelation
```
It works good.
Thank you for your help.
happy new  year 😀
