### ISSUE TITLE
Write lists for many keys to Redis

### ISSUE THREAD

**Issue by frederic-schmaljohann** [RedisLabs/spark-redis#217]
I would like to write lists values for multiple keys with spark-redis.

The data structure I would like to write is basically `key:String, value:List[String]`.

Using regular redis commands I would use `LPUSH` for example.

So far I have only found sc.toRedisLIST which doesn't seem to support multiple keys.

Am I missing something?

Thanks in advance

**Comment by fe2s** [comment]
Hi @frederic-schmaljohann ,
The API your are looking for is missing, but shouldn't be a problem to add that. I will try to implement it on the weekend.

**Comment by frederic-schmaljohann** [comment]
Thanks for implementing this @fe2s . When do you think the change will be released?

**Comment by fe2s** [comment]
Hi @frederic-schmaljohann ,
The PR https://github.com/RedisLabs/spark-redis/pull/216 was to address issue #205 which is similar to your request, but we needed byte oriented API. Actually you can use `toRedisByteLIST` from that PR if you convert strings to byte arrays before saving. However I still want to have a similar function, but the one that works with strings. I will let you know once it's ready.

**Comment by fe2s** [comment]
Added [`toRedisLISTs`](https://github.com/RedisLabs/spark-redis/blob/master/doc/rdd.md#lists-1) API
Will be released in 2.4.2
