### ISSUE TITLE
Why DStream of streaming and structured streaming has different schema

### ISSUE THREAD

**Issue by Litchilitchy** [RedisLabs/spark-redis#218]
When we use xadd to redis, the schema is {key: value} pair with a stream id

In spark-redis structured streaming, the schema is 
```
spark
      .readStream
      .format("redis")
      .option("stream.keys", stream_key)
      .schema(StructType(Array(
        StructField(key, value)
```

But in streaming, users are required to set group name and consumer name like
```
ssc.createRedisXStream(Seq(ConsumerConfig(stream_key, XXX, XXX)))
```
I do not know the value of XXX, because in structured streaming, they are not values needed to be provided. And I use above code trying to get value from redis, it does not work. 

And in structured streaming, when redis has no new data, query will not be activated, and in streaming it just continuously get the empty RDD.

How to make it work in streaming?

**Comment by fe2s** [comment]
Hi @Litchilitchy ,

`ssc.createRedisXStream(Seq(ConsumerConfig(stream_key, XXX, XXX)))`
those parameters are `consumer group name` and `consumer name`. You can choose any names for your application, e.g.:
`ssc.createRedisXStream(Seq(ConsumerConfig(stream_key, "consumer-group-1", "consumer-1")))`. Consumer group will be created by library automatically if doesn't exist.

Does it answer your question?

**Comment by Litchilitchy** [comment]
@fe2s Thanks, got the answer.

And the reason spark streaming seems does not work is due to my wrong operations. closed
