### ISSUE TITLE
How do you batch read to return an array

### ISSUE THREAD

**Issue by xingshaoqi** [RedisLabs/spark-redis#234]

**Comment by xingshaoqi** [comment]
You need to read redis in RDD that relies on RDD's data, but you want it to return an array

**Comment by fe2s** [comment]
Hi @xingshaoqi,
I didn't get the question. Can you please provide some example?

**Comment by xingshaoqi** [comment]
@fe2s rdd.mapPartitions(it=>{
val arr=redis.fromRedisHash(it) //Passing in an array returns an array, referenced inside RDD
})

**Comment by fe2s** [comment]
There is no such API to achieve that.
