### ISSUE TITLE
Potential inconsistency in parameters definition

### ISSUE THREAD

**Issue by felipemmelo** [RedisLabs/spark-redis#238]
Hi there, 

Foremost, congrats and thanks for this work!

I am trying to run a query that gets a key pattern from a table like this:

      spark.read 
      .format("org.apache.spark.sql.redis")
      .option("table", "person")
      .option("key.column", "name")
      .option("keys.pattern", "F*")
      .load()

In [this line](https://github.com/RedisLabs/spark-redis/blob/master/src/main/scala/org/apache/spark/sql/redis/RedisSourceRelation.scala#L104) you only allow either, table or key pattern. 

However, if I do not set the table name, I get an error [right here](https://github.com/RedisLabs/spark-redis/blob/master/src/main/scala/org/apache/spark/sql/redis/RedisSourceRelation.scala#L208).

Shouldn't these two settings **not** be be mutually exclusive?

Thanks again.

**Comment by fe2s** [comment]
Hi @felipemmelo ,
there are two mutual exclusive options: read previously saved table via `table` parameter or read by keys pattern.

**Comment by felipemmelo** [comment]
Hi @fe2s , thanks for the quick reply.

Not sure I followed. Which option(s) should I use to read _keys_ starting with _F_ from a table called **person**?

**Comment by fe2s** [comment]
If you are following the examples from here https://github.com/RedisLabs/spark-redis/blob/master/doc/dataframe.md#reading you should be able to read it with
```scala
val df = spark.read
              .format("org.apache.spark.sql.redis")
              .schema(
                StructType(Array(
                  StructField("id", IntegerType),
                  StructField("name", StringType),
                  StructField("age", IntegerType))
                )
              )
              .option("keys.pattern", "person:F*")
              .option("key.column", "id")
              .load()
```

If you previously saved the dataframe as a table, you can read the schema first and then use it in your loading. E.g.

```scala
val schema = spark.read
                        .format("org.apache.spark.sql.redis")
                        .option("table", "person")
                        .load()
                       .schema

val df = spark.read
              .format("org.apache.spark.sql.redis")
              .schema(schema)
              .option("keys.pattern", "person:F*")
              .option("key.column", "id")
              .load()
```

Other option is to read the entire table and then filter out rows using regular DataFrame filter. But in this case you have read all the data from table to Spark memory. E.g.
```scala
val df = spark.read
                        .format("org.apache.spark.sql.redis")
                        .option("table", "person")
                        .load()
                        .filter($"name".startsWith(lit("F")))
                       
```

Note: I didn't test any of the code snippets.

**Comment by felipemmelo** [comment]
Thanks!
