### ISSUE TITLE
sparksql 不能连接到redis

### ISSUE THREAD

**Issue by xjxjin** [RedisLabs/spark-redis#279]
麻烦帮忙看看什么原因 redis确定是好的

redis deployement：sentinel
redis version：Redis server v=4.0.14 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=a9546b4e3153e7e3

        <dependency>
            <groupId>com.redislabs</groupId>
            <artifactId>spark-redis_2.11</artifactId>
            <version>2.5.0</version>
        </dependency>

![image](https://user-images.githubusercontent.com/35513148/102454783-7f8b7b00-4079-11eb-984d-5d457041fe20.png)
![image](https://user-images.githubusercontent.com/35513148/102454897-acd82900-4079-11eb-8081-c55fe868ebb8.png)
![image](https://user-images.githubusercontent.com/35513148/102454940-bfeaf900-4079-11eb-92a1-ab81f9b453e8.png)

**Comment by ighack** [comment]
.conf("spark.redis.ssl", true)
有认证试一下这个值吧

spark.redis.db这个值官方好像说避免使用
