### ISSUE TITLE
toRedisKV method can't handle a large data

### ISSUE THREAD

**Issue by okaoka** [RedisLabs/spark-redis#3]
I faced NegativeArraySizeException because of the memory shortage while handling a large data.
i.e. the data size is over 20GB, the cluster has about 60 machines(each has 128GB memory)  

I think groupByKey function is the cause of this problem, because groupByKey has a risk of consuming  memory of the just one machine.

see:
```
http://mail-archives.us.apache.org/mod_mbox/spark-user/201409.mbox/<1410135789380-13669.post@n3.nabble.com>
```

**Comment by sunheehnus** [comment]
Hello @okaoka , sorry for the delay, I didn't notice the report, feedback will come ASAP. Thanks very much.

**Comment by sunheehnus** [comment]
Hello @okaoka , already pushed a new path for this, thanks very much :-)

**Comment by okaoka** [comment]
Hi @sunheehnus 
Thank  you for your kindness !
