### ISSUE TITLE
INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by YINGPENGZH** [RedisLabs/spark-redis#301]
I fail to inert three words in redis by using spark,  and always get java.lang.ArrayIndexOutOfBoundsException: 0. My spark version is 2.4 and spark-redis_2.11. 

val wc = sc.parallelize(List(
      ("hello", "1")
    ))
    sc.toRedisHASH(wc, "map1")
    sc.toRedisHASH(wc, "map2")
    sc.toRedisHASH(wc, "map3")

**Comment by fe2s** [comment]
Hi @YINGPENGZH , 
I cannot reproduce, works for me.
Could you please share the full listing of stack trace and the full listing of your code?

**Comment by YINGPENGZH** [comment]
> Hi @YINGPENGZH ,
> I cannot reproduce, works for me.
> Could you please share the full listing of stack trace and the full listing of your code?

I find the problem, our clusters lead to spark-redis cannot connect success, thank you so much.
