### ISSUE TITLE
Spark DataSets support

### ISSUE THREAD

**Issue by dvirsky** [RedisLabs/spark-redis#32]
now that we support data frames we could also support data sets. 
could be a task for Shay

cc: @Yiftach

**Comment by MostafaAlaa2016** [comment]
+1

**Comment by gkorland** [comment]
We are working to rewrite the dataframes/datasets support.
@sylvinho81 can you please extend on your use case so we can make sure we cover it?

**Comment by sylvinho81** [comment]
@gkorland the thing is that right now this connector just works with rdd. In my case I am using Dataframes. So in order to use this connector I have to do something like this:

val hash = df.select("key", "date").map(r => (r.getString(0), r.getString(1))).rdd
sc.toRedisHASH(hash, "processed_" + timestamp.toString.replaceAll(" ", "_"))

**Comment by gkorland** [comment]
@sylvinho81 thanks for the code example.
@fe2s just pushed some initial "native" support for DataFrames see - https://github.com/RedisLabs/spark-redis/tree/dataframe

**Comment by sumanentc** [comment]
When DataSet support will be release .

**Comment by fe2s** [comment]
The preview of DataFrame/Dataset is now available in https://github.com/RedisLabs/spark-redis/tree/dataframe 
Documentation https://github.com/RedisLabs/spark-redis/blob/dataframe/doc/dataframe.md

Any feedback is appreciated.

**Comment by sumanentc** [comment]
Can we specify multiple key columns while saving the Dataset to Redis. Also how can we achieve the same in Spark Sql.

**Comment by fe2s** [comment]
Multiple key columns are not supported, but you can create an artificial column with Spark by concatenating several columns and then use that column as a key. Here is an example:

```scala
case class Person(firstName: String, lastName: String, age: Int)

val personSeq = Seq(Person("John", "Doe", 30), Person("Richard", "Roe", 45))
val df = spark.createDataFrame(personSeq)
import org.apache.spark.sql.functions.{concat, lit}
import spark.implicits._
val withFullName = df.withColumn("fullname", concat($"firstName", lit("_"), $"lastName"))

withFullName.write
  .format("org.apache.spark.sql.redis")
  .option("table", "person")
  .option("key.column", "fullname")
  .mode(SaveMode.Overwrite)
  .save()
```

**Comment by sumanentc** [comment]
which all languages are supported in version 2.3.1

**Comment by fe2s** [comment]
Datasets/dataframes are available in all languages: Scala, Java, Python and R
