### ISSUE TITLE
Spark3.0.x support. 

### ISSUE THREAD

**Issue by kaijiezhang0319** [RedisLabs/spark-redis#322]
Hello redis folks, i see this library's latest version is 2.6 which support spark2.4.x.   From the readme, the next release would be support in spark3.0.x.   I want to know what is your plan for the next release, any ETA for that.  Thanks

**Comment by fe2s** [comment]
spark-redis 3.0.0 is built with Spark 3
https://search.maven.org/artifact/com.redislabs/spark-redis_2.12/3.0.0/jar
