### ISSUE TITLE
How ttl works when SaveMode.Ignore

### ISSUE THREAD

**Issue by hyungryuk** [RedisLabs/spark-redis#326]
Is ignored key's ttl also reset?

**Comment by fe2s** [comment]
if dataframe exists in Redis - the entire save operation is ignored

**Comment by hyungryuk** [comment]
@fe2s thanx a lot.
btw.. i just realized that Ignore mode also ignores dataframe key column when checking if the key exist.
so no matter key column value is, all rows with same tablename are ignored!
