### ISSUE TITLE
Unable to create table using spark.sql

### ISSUE THREAD

**Issue by karthick30121990** [RedisLabs/spark-redis#330]
![image](https://user-images.githubusercontent.com/95172150/143767950-225920a6-fd0e-4201-aba6-4471691ea500.png)
![image](https://user-images.githubusercontent.com/95172150/143767971-301b9404-c63e-4f11-8f69-55c3927988a8.png)

var spark = SparkSession.Builder()
                    .AppName("Redis-cache")
                    .Master("local[*]")
                    .Config("spark.redis.host", "localhost")
                    .Config("spark.redis.port", "6379")
                    .GetOrCreate();

DataFrame sdf = spark.Sql("CREATE TABLE IF NOT EXISTS clicks(asset STRING, count INT) USING org.apache.spark.sql.redis OPTIONS(table 'clicks',key.column 'asset')");

**Comment by fe2s** [comment]
Hi @karthick30121990, it looks like something is wrong with your classpath, Scala is missing there. How do you run it?

**Comment by sazzad16** [comment]
Closed due to inactivity.
