### ISSUE TITLE
 sql word :Could not get a resource from the pool (state=,code=0)

### ISSUE THREAD

**Issue by zehui-liu** [RedisLabs/spark-redis#338]
I  use this sql word :
create table test06(
a1 string,
a2 int,
a3 int
)using org.apache.spark.sql.redis OPTIONS (table 'test1',spark.redis.host '127.0.0.1' , spark.redis.port '6379');
 on spark thrift server . but it does not working.Does it support this sql ?

**Comment by fe2s** [comment]
Hi @Zhl-zero-bytes ,
can you try this? https://github.com/RedisLabs/spark-redis/blob/master/doc/dataframe.md#spark-sql

**Comment by sazzad16** [comment]
Closed due to inactivity.
