### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by SmileTM** [RedisLabs/spark-redis#361]
<dependency>
            <groupId>com.redislabs</groupId>
            <artifactId>spark-redis_2.12</artifactId>
            <version>3.0.0</version>
</dependency>

spark yarn  submitted  run error:

`
User class threw exception: java.lang.NoSuchMethodError: redis.clients.jedis.JedisPoolConfig.setSoftMinEvictableIdleTime(Ljava/time/Duration;)Vat com.redislabs.provider.redis.ConnectionPool$.$anonfun$connect$1(ConnectionPool.scala:24)at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:97)at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:94)at scala.collection.convert.Wrappers$JConcurrentMapWrapper.getOrElseUpdate(Wrappers.scala:333)at com.redislabs.provider.redis.ConnectionPool$.connect(ConnectionPool.scala:17)at com.redislabs.provider.redis.RedisEndpoint.connect(RedisConfig.scala:94)at com.redislabs.provider.redis.RedisConfig.clusterEnabled(RedisConfig.scala:227)at com.redislabs.provider.redis.RedisConfig.getNodes(RedisConfig.scala:367)at com.redislabs.provider.redis.RedisConfig.getHosts(RedisConfig.scala:267)at com.redislabs.provider.redis.RedisConfig.<init>(RedisConfig.scala:166)at com.redislabs.provider.redis.RedisConfig$.fromSparkConf(RedisConfig.scala:150)at com.redislabs.provider.redis.RedisContext.toRedisKV$default$3(redisFunctions.scala:251)
`

how to solve this problem？

**Comment by sidartha** [comment]
@SmileTM How did you solve this issue? I am running into the same problem
