### ISSUE TITLE
Do you consider supporting Spark to directly read and parse Redis RDB files as key value pairs?

### ISSUE THREAD

**Issue by youngxinler** [RedisLabs/spark-redis#363]
Direct reading of online databases for full database analysis may have an impact on online services, but direct reading of RDB files will not.

It can even further support Spark to produce RDB files. Writing KV files to Redis through RDB files is faster and more efficient.

**Comment by sazzad16** [comment]
Directly reading/parsing Redis RDB files are not going to be suppoted, at least in recent future.
