### ISSUE TITLE
Scala and Spark 2.11 support

### ISSUE THREAD

**Issue by olegnikolaenkoib** [RedisLabs/spark-redis#39]
Could you please add support Scala and Spark for version 2.11 ?

**Comment by mmroden** [comment]
+1

**Comment by StevenChennet** [comment]
+1

**Comment by srikanth235** [comment]
+1

**Comment by MostafaAlaa2016** [comment]
+1

**Comment by CompuGain-Sol** [comment]
+1

**Comment by cnumutyala** [comment]
+1

**Comment by gkorland** [comment]
v2.3.0 released and you can get the artifacte from here
https://oss.sonatype.org/content/groups/staging/com/redislabs/spark-redis/2.3.0/
