### ISSUE TITLE
Library dependencies 

### ISSUE THREAD

**Issue by nguyenvinhtriet** [RedisLabs/spark-redis#57]
Hi,

I try 2 ways to add spark-redis dependencies:
- Grable
- SBT
and this is error message:
![screenshot from 2017-08-23 11-01-00](https://user-images.githubusercontent.com/19217841/29598330-79b60580-87f2-11e7-8648-7458cbf0bb16.png)
 If i add library via jar file, it's ok. Please help to check this issue.

Thanks,
TrietNV

**Comment by Lakshmihm** [comment]
I am facing the same issue. Please advice

**Comment by itamarhaber** [comment]
Hi all,

Please stay patient - we're looking into these issues and will hopefully resolve then asap.

**Comment by sylvinho81** [comment]
thanks for your answer @itamarhaber . Just one thing, any to other way to add the jar inside my project so I can compile and generate the final jar, in order to execute it through spark-submit.

**Comment by sylvinho81** [comment]
@nguyenvinhtriet @Lakshmihm this should work for you:

libraryDependencies += "redis.clients" % "jedis" % "2.9.0"
libraryDependencies += "org.apache.commons" % "commons-pool2" % "2.5.0"
libraryDependencies += "org.apache.spark" %% "spark-streaming" % "2.3.0" % "provided"

libraryDependencies += "RedisLabs" % "spark-redis" % "0.3.2" from "https://dl.bintray.com/spark-packages/maven/RedisLabs/spark-redis/0.3.2/spark-redis-0.3.2.jar"

**Comment by fe2s** [comment]
Closing sine the suggested solution was provided and ticket is outdated.
