### ISSUE TITLE
How to reduce QPS when spark writes redis

### ISSUE THREAD

**Issue by todd-pro** [RedisLabs/spark-redis#63]
Two hundred thousand data using Spark imported from hive redis, QPS found too high, there is a way to control the speed of writing it?

**Comment by MaiSuiYuMi** [comment]
I also have this issue, is there any solution for this?

**Comment by fe2s** [comment]
You can try to decrease the number of RDD/DataFrame partitions, it implies the level of parallelism used by Spark.
