### ISSUE TITLE
Support write/read spark Dataframe or Dataset?

### ISSUE THREAD

**Issue by ZanZong** [RedisLabs/spark-redis#65]
Hi, I'm lucky to find this project to store RDD to Redis. But the code has not been updated for a long time, and I can't find the corresponding document for #32. Can we support Dataframe or Dataset now?
thanks!

**Comment by itamarhaber** [comment]
Hello all,

We're working on updating this project to include support for the DataFrame API - stay tuned.

**Comment by gkorland** [comment]
See #32
