### ISSUE TITLE
Can someone please add the latest changes to maven repo?

### ISSUE THREAD

**Issue by nitpil** [RedisLabs/spark-redis#66]
Looking at the commit history, Shay Nativ has added compatibility to spark 2.1 on Oct 2017. We are planning on using this connector for our Spark Redis combo. It will be highly beneficial to everyone if someone can build and add this connector's latest build/jar file to the maven repository so that we don't have to build and maintain a private repo for the latest changes.

**Comment by gkorland** [comment]
2.3.0 and 1.4.1 were released 
(All the builds can be found here https://oss.sonatype.org/content/groups/staging/com/redislabs/spark-redis/)
