### ISSUE TITLE
Maven build failed for Oozie 4.3.0

### ISSUE THREAD

**Issue by fadishaar84** [RedisLabs/spark-redis#70]
I want to use Oozie for automating Spark Jobs. I'm trying to build Oozie using Maven 3.3.9. I have modified pom.xml file for hadoop 2.7.1, java 1.7, hbase 1.2.0, oozie 4.3.0, I got the error described below during ./mkdistro.sh Maven build command. It sounds like it is related to hbase credentials class. what modifications I have to do to pass this error?

 [INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ oozie-core ---
    [INFO] Compiling 517 source files to /usr/lib/oozie/oozie-4.3.0/core/target/classes
    [INFO] -------------------------------------------------------------
    [ERROR] COMPILATION ERROR : 
    [INFO] -------------------------------------------------------------
    [ERROR] /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[28,45] error: package org.apache.hadoop.hbase.security.token does not exist
    [ERROR] /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[29,45] error: package org.apache.hadoop.hbase.security.token does not exist
    [ERROR] /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[83,14] error: cannot find symbol
    [ERROR]  class HbaseCredentials
    /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[84,48] error: cannot find symbol
    [ERROR]  class HbaseCredentials
    /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[85,29] error: cannot find symbol
    [ERROR]  class AuthenticationTokenIdentifier
    /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[86,27] error: cannot find symbol
    [INFO] 6 errors 
    [INFO] -------------------------------------------------------------
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] Apache Oozie Main .................................. SUCCESS [  2.452 s]
    [INFO] Apache Oozie Hadoop Utils hadoop-2-4.3.0 ........... SUCCESS [  4.780 s]
    [INFO] Apache Oozie Hadoop Distcp hadoop-2-4.3.0 .......... SUCCESS [  0.151 s]
    [INFO] Apache Oozie Hadoop Auth hadoop-2-4.3.0 Test ....... SUCCESS [  0.698 s]
    [INFO] Apache Oozie Hadoop Libs ........................... SUCCESS [  0.082 s]
    [INFO] Apache Oozie Client ................................ SUCCESS [ 19.330 s]
    [INFO] Apache Oozie Share Lib Oozie ....................... SUCCESS [  4.273 s]
    [INFO] Apache Oozie Share Lib HCatalog .................... SUCCESS [  4.933 s]
    [INFO] Apache Oozie Share Lib Distcp ...................... SUCCESS [  1.104 s]
    [INFO] Apache Oozie Core .................................. FAILURE [ 11.598 s]
    [INFO] Apache Oozie Share Lib Streaming ................... SKIPPED
    [INFO] Apache Oozie Share Lib Pig ......................... SKIPPED
    [INFO] Apache Oozie Share Lib Hive ........................ SKIPPED
    [INFO] Apache Oozie Share Lib Hive 2 ...................... SKIPPED
    [INFO] Apache Oozie Share Lib Sqoop ....................... SKIPPED
    [INFO] Apache Oozie Examples .............................. SKIPPED
    [INFO] Apache Oozie Share Lib Spark ....................... SKIPPED
    [INFO] Apache Oozie Share Lib ............................. SKIPPED
    [INFO] Apache Oozie Docs .................................. SKIPPED
    [INFO] Apache Oozie WebApp ................................ SKIPPED
    [INFO] Apache Oozie Tools ................................. SKIPPED
    [INFO] Apache Oozie MiniOozie ............................. SKIPPED
    [INFO] Apache Oozie Distro ................................ SKIPPED
    [INFO] Apache Oozie ZooKeeper Security Tests .............. SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 52.026 s
    [INFO] Finished at: 2018-07-25T11:42:47+03:00
    [INFO] Final Memory: 127M/797M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project oozie-core: Compilation failure: Compilation failure:
    [ERROR] /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[28,45] error: package org.apache.hadoop.hbase.security.token does not exist
    [ERROR] /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[29,45] error: package org.apache.hadoop.hbase.security.token does not exist
    [ERROR] /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[83,14] error: cannot find symbol
    [ERROR] class HbaseCredentials
    [ERROR] /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[84,48] error: cannot find symbol
    [ERROR] class HbaseCredentials
    [ERROR] /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[85,29] error: cannot find symbol
    [ERROR] class AuthenticationTokenIdentifier
    [ERROR] /usr/lib/oozie/oozie-4.3.0/core/src/main/java/org/apache/oozie/action/hadoop/HbaseCredentials.java:[86,27] error: cannot find symbol
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

**Comment by fadishaar84** [comment]
I'm sorry, this issue is not related to spark-redis, I added it by mistake. I hope if you can move it to maven or oozie section.

**Comment by fe2s** [comment]
Closing as not relevant
