### ISSUE TITLE
duplicate tests

### ISSUE THREAD

**Issue by fe2s** [RedisLabs/spark-redis#71]
There are two versions of each and every integration test: standalone and cluster (e.g. KeysClusterSuite and KeysStandaloneSuite). The code is identical with the only difference in Redis port number and authentication.

It should be refactored to remove duplicate code.

**Comment by fe2s** [comment]
This is fixed in `dataframe` branch.

**Comment by justinrmiller** [comment]
@fe2s Can this ticket be closed then?
