### ISSUE TITLE
can l use spark-redis in scala 2.11 and spark 2.3 ???

### ISSUE THREAD

**Issue by wenfang6** [RedisLabs/spark-redis#72]
how can l use spark-redis in scala 2.11 and spark2.3 ?

**Comment by fe2s** [comment]
Hi @wenfang6,

There is a work-in-progress branch with Spark 2.3 and Scala 2.11 https://github.com/RedisLabs/spark-redis/tree/branch-2.3. It is not published to maven central and not officially released yet, but you can build the branch by yourself and start using it.
 
It will build the following artifact:
```
 <dependency>
       <groupId>com.redislabs</groupId>
       <artifactId>spark-redis</artifactId>
       <version>2.3.0</version>
</dependency>
```

**Comment by gkorland** [comment]
You can get the official version from here  - https://oss.sonatype.org/content/groups/staging/com/redislabs/spark-redis/2.3.0/
