### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by ScottWang** [RedisLabs/spark-redis#8]
Is there a way to pass in authentication credential for the connection?

**Comment by dvirsky** [comment]
We're working on a refactor that will make this easier, it should be ready in a couple of days.

**Comment by ScottWang** [comment]
Is there a branch that I can use first?  We have an internal redislabs system that we would like to test using this library.

**Comment by dvirsky** [comment]
There is a PR enabling this, though the approach we're taking will be different (which is why it's not merged) - it does work. https://github.com/RedisLabs/spark-redis/pull/5

**Comment by dvirsky** [comment]
BTW may I ask what would be your use case for this? Feel free to email me directly if you want, dvir at redislabs dot com

**Comment by dvirsky** [comment]
Fixed in master after configuration refactor.
