### ISSUE TITLE
how to set expire time of redis' keys

### ISSUE THREAD

**Issue by shenzhun** [RedisLabs/spark-redis#9]
Hi there,

I checked the code and doc, and could not find how to set expire time of keys? Did I missing something or this function was not provided? 

Thanks.

**Comment by dvirsky** [comment]
Hi, it's not implemented yet.
Would mind expanding a bit on what is the use case for it?

**Comment by shenzhun** [comment]
Hi dvirsky,

I use spark to do calculate item similarity, the output is item_id( key) and its related items( value). I run it once a day, update the data in redis. If a key is not update after two days, it should be delete automatically. So I need to set the expire time of every key.

**Comment by dvirsky** [comment]
OK, I see. Let us think about how to best do it. 
You are more than welcome to suggest how you'd like to see it implemented! 

Thanks.

**Comment by dvirsky** [comment]
Merging with #11
