### ISSUE TITLE
build.sbt is not updated for the branch 2.3

### ISSUE THREAD

**Issue by Stanpol** [RedisLabs/spark-redis#91]
In particular I'm interested to work with Spark 2.3, however build.sbt in every branch has old spark-redis `version := "0.3.2"` and `sparkVersion := "1.4.0"`

**Comment by fe2s** [comment]
I think that maven is an official build tool that is supported and used by CI.
Is there a reason you can not build with maven?

We should remove build.sbt from the project if it's not supported.
@gkorland , what do you think?

**Comment by Stanpol** [comment]
Maven worked fine for me, I just started by default with sbt.

If you go with Maven as default, I would recommend to add to the documentation an example for users without maven, something like  `docker run -it --rm --name my-maven-project -v ~/spark-redis:/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean package -DskipTests` so anyone without maven installed on their system can quickly compile spark-redis.

**Comment by fe2s** [comment]
SBT build was not supported for a long time and was completely removed in Spark-Redis 2.4.0.
Closing this issue.
